// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/ingester.proto

package duckdbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushRequest represents a write request
type PushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SQL statement to execute
	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	// Partition key for routing
	PartitionKey string `protobuf:"bytes,2,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	// Optional tenant ID for multi-tenancy
	TenantId      string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_proto_ingester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_ingester_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *PushRequest) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *PushRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// PushResponse represents the result of a write
type PushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of rows affected
	RowsAffected int64 `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	// Shard ID that handled the write
	ShardId int32 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Error message if write failed (empty on success)
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_proto_ingester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_proto_ingester_proto_rawDescGZIP(), []int{1}
}

func (x *PushResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *PushResponse) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *PushResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_ingester_proto protoreflect.FileDescriptor

const file_proto_ingester_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ingester.proto\x12\x11duckdb.cluster.v1\x1a\x12proto/common.proto\"a\n" +
	"\vPushRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12#\n" +
	"\rpartition_key\x18\x02 \x01(\tR\fpartitionKey\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"d\n" +
	"\fPushResponse\x12#\n" +
	"\rrows_affected\x18\x01 \x01(\x03R\frowsAffected\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xa9\x01\n" +
	"\x0fIngesterService\x12G\n" +
	"\x04Push\x12\x1e.duckdb.cluster.v1.PushRequest\x1a\x1f.duckdb.cluster.v1.PushResponse\x12M\n" +
	"\x06Health\x12 .duckdb.cluster.v1.HealthRequest\x1a!.duckdb.cluster.v1.HealthResponseB0Z.github.com/brown/duckdb-cluster/proto/duckdbv1b\x06proto3"

var (
	file_proto_ingester_proto_rawDescOnce sync.Once
	file_proto_ingester_proto_rawDescData []byte
)

func file_proto_ingester_proto_rawDescGZIP() []byte {
	file_proto_ingester_proto_rawDescOnce.Do(func() {
		file_proto_ingester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ingester_proto_rawDesc), len(file_proto_ingester_proto_rawDesc)))
	})
	return file_proto_ingester_proto_rawDescData
}

var file_proto_ingester_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ingester_proto_goTypes = []any{
	(*PushRequest)(nil),    // 0: duckdb.cluster.v1.PushRequest
	(*PushResponse)(nil),   // 1: duckdb.cluster.v1.PushResponse
	(*HealthRequest)(nil),  // 2: duckdb.cluster.v1.HealthRequest
	(*HealthResponse)(nil), // 3: duckdb.cluster.v1.HealthResponse
}
var file_proto_ingester_proto_depIdxs = []int32{
	0, // 0: duckdb.cluster.v1.IngesterService.Push:input_type -> duckdb.cluster.v1.PushRequest
	2, // 1: duckdb.cluster.v1.IngesterService.Health:input_type -> duckdb.cluster.v1.HealthRequest
	1, // 2: duckdb.cluster.v1.IngesterService.Push:output_type -> duckdb.cluster.v1.PushResponse
	3, // 3: duckdb.cluster.v1.IngesterService.Health:output_type -> duckdb.cluster.v1.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ingester_proto_init() }
func file_proto_ingester_proto_init() {
	if File_proto_ingester_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ingester_proto_rawDesc), len(file_proto_ingester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ingester_proto_goTypes,
		DependencyIndexes: file_proto_ingester_proto_depIdxs,
		MessageInfos:      file_proto_ingester_proto_msgTypes,
	}.Build()
	File_proto_ingester_proto = out.File
	file_proto_ingester_proto_goTypes = nil
	file_proto_ingester_proto_depIdxs = nil
}
