// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/querier.proto

package duckdbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryRequest represents a query to execute
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SQL query to execute
	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	// Optional: specific shard IDs to query (empty = all shards)
	ShardIds      []int32 `protobuf:"varint,2,rep,packed,name=shard_ids,json=shardIds,proto3" json:"shard_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_querier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_querier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_querier_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetShardIds() []int32 {
	if x != nil {
		return x.ShardIds
	}
	return nil
}

// QueryResponse represents query results
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column names
	Columns []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	// Rows as JSON-encoded values
	Rows []*Row `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	// Error message if query failed (empty on success)
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_querier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_querier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_querier_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Row represents a single row of data
type Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column values as JSON strings
	// (we use JSON encoding to handle DuckDB's flexible type system)
	Values        map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_querier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_querier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_querier_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_querier_proto protoreflect.FileDescriptor

const file_proto_querier_proto_rawDesc = "" +
	"\n" +
	"\x13proto/querier.proto\x12\x11duckdb.cluster.v1\x1a\x12proto/common.proto\"=\n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x1b\n" +
	"\tshard_ids\x18\x02 \x03(\x05R\bshardIds\"k\n" +
	"\rQueryResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12*\n" +
	"\x04rows\x18\x02 \x03(\v2\x16.duckdb.cluster.v1.RowR\x04rows\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"|\n" +
	"\x03Row\x12:\n" +
	"\x06values\x18\x01 \x03(\v2\".duckdb.cluster.v1.Row.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xab\x01\n" +
	"\x0eQuerierService\x12J\n" +
	"\x05Query\x12\x1f.duckdb.cluster.v1.QueryRequest\x1a .duckdb.cluster.v1.QueryResponse\x12M\n" +
	"\x06Health\x12 .duckdb.cluster.v1.HealthRequest\x1a!.duckdb.cluster.v1.HealthResponseB0Z.github.com/brown/duckdb-cluster/proto/duckdbv1b\x06proto3"

var (
	file_proto_querier_proto_rawDescOnce sync.Once
	file_proto_querier_proto_rawDescData []byte
)

func file_proto_querier_proto_rawDescGZIP() []byte {
	file_proto_querier_proto_rawDescOnce.Do(func() {
		file_proto_querier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_querier_proto_rawDesc), len(file_proto_querier_proto_rawDesc)))
	})
	return file_proto_querier_proto_rawDescData
}

var file_proto_querier_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_querier_proto_goTypes = []any{
	(*QueryRequest)(nil),   // 0: duckdb.cluster.v1.QueryRequest
	(*QueryResponse)(nil),  // 1: duckdb.cluster.v1.QueryResponse
	(*Row)(nil),            // 2: duckdb.cluster.v1.Row
	nil,                    // 3: duckdb.cluster.v1.Row.ValuesEntry
	(*HealthRequest)(nil),  // 4: duckdb.cluster.v1.HealthRequest
	(*HealthResponse)(nil), // 5: duckdb.cluster.v1.HealthResponse
}
var file_proto_querier_proto_depIdxs = []int32{
	2, // 0: duckdb.cluster.v1.QueryResponse.rows:type_name -> duckdb.cluster.v1.Row
	3, // 1: duckdb.cluster.v1.Row.values:type_name -> duckdb.cluster.v1.Row.ValuesEntry
	0, // 2: duckdb.cluster.v1.QuerierService.Query:input_type -> duckdb.cluster.v1.QueryRequest
	4, // 3: duckdb.cluster.v1.QuerierService.Health:input_type -> duckdb.cluster.v1.HealthRequest
	1, // 4: duckdb.cluster.v1.QuerierService.Query:output_type -> duckdb.cluster.v1.QueryResponse
	5, // 5: duckdb.cluster.v1.QuerierService.Health:output_type -> duckdb.cluster.v1.HealthResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_querier_proto_init() }
func file_proto_querier_proto_init() {
	if File_proto_querier_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_querier_proto_rawDesc), len(file_proto_querier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_querier_proto_goTypes,
		DependencyIndexes: file_proto_querier_proto_depIdxs,
		MessageInfos:      file_proto_querier_proto_msgTypes,
	}.Build()
	File_proto_querier_proto = out.File
	file_proto_querier_proto_goTypes = nil
	file_proto_querier_proto_depIdxs = nil
}
