target: write

common:
  data_dir: /data
  num_shards: 3
  log_level: info

server:
  http_listen_addr: ":8080"
  grpc_listen_addr: ":9095"

ring:
  instance_id: write-node
  instance_addr: "write-node:9095"
  memberlist:
    bind_addr: "0.0.0.0"
    bind_port: 7946
    join_peers:
      - "write-node:7946"
      - "read-node:7946"
      - "all-node:7946"

distributor:
  replication_factor: 1
  use_local_ingester: true

observability:
  metrics:
    enabled: true
    path: /metrics
  logging:
    level: info
    format: text
